#fone=("телефон")
def num(fone):
    print("Набери 1," +fone)
    print("Набери 2," +fone)
    print("Набери 3," +fone)
    print("Набери 4," +fone)
    print("Набери 5," +fone)
    print("Набери 6," +fone)
    print("Набери 7," +fone)
    print("Набери 8," +fone)
    print("Набери 9," +fone)
    print("Набери 10," +fone)
    print("Набери 11," +fone)
num("88005553535")